Examples can now be run without errors, also some typos fixed
NLESC-JCER/QMCTorch pull request #89
Opened 2021-03-11 11:00 UTC by matthijsdewit111

SolverBase.task was never set, so removed
SolverOrbital.chkpt_every was not always set, so use get_attr with default value for logging attributes
SolverBase.save_checkpoint() no longer returns loss
plot_data couldn't find attribute, now plots attribute of best model

2021-03-11 12:52 UTC, NicoRenaud requested changes
Thanks good work ! I have very minor comment in the PR.
One thing though is that the solver_horovod is never tested on GitHub Action. However we can run MPI processes on GA so i think we should be able to have a very small test just to make sure that the solver runs. Could you look into that since you fixed the solver_horovod in that PR ?

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_base.py
> +        if self.opt is not None and 'lpos_needed' not in self.opt.__dict__.keys():
good catch ! We can potentially not have an optimizer !

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital.py
> +                hdf5_group='geo_opt', chkpt_every=None, tqdm=False):
great thanks !

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_base.py
> -
why should we remove that part ?

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital.py
> +        self.log_data_opt(nepoch, hdf5_group)
oh yeah that's better :)

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital.py
> +        self.log_data_opt(nepoch, hdf5_group)
I'm not sure what's best here. The group in the hdf5 file could be different from the task. But I agree that it could be simplified.

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital.py
> +            '  Checkpoint every    : {0}', getattr(self, 'chkpt_every', None))
why is that needed ?

2021-03-11 12:52 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital_horovod.py
> +            clip_loss=False, grad='manual', hdf5_group='optimization',
in principle we could do wave function or geometry optimization. So maybe de default group could be wf_opt

2021-03-11 13:04 UTC, matthijsdewit111 commented on qmctorch/solver/solver_base.py
> -
We can keep the second part of the if statement, I'll put it back in. The first part of the if statement isn't needed since self.task is never assigned I found.

2021-03-11 13:17 UTC, matthijsdewit111 commented on qmctorch/solver/solver_orbital.py
> +            '  Checkpoint every    : {0}', getattr(self, 'chkpt_every', None))
When I ran the Horovod example, it never executed SolverOrbital.prepare_optimization() (where self.chkpt_every is assigned), so we should either assign it always somehow or make it optional, I agree this right now is not the best solution, but I just wanted it to run :)
I think it has to do with the fact that SolverOrbitalHorovod never used the chkpt_every before, it only saved checkpoints if it found a lower energy state.
So should I change SolverOrbitalHorovod.run() to saving a checkpoint every few iteration and making sure it sets self.chkpt_every, or we make it optional and just default to None in the SolverOrbital.init(), so the attribute always exists at least.

2021-03-11 18:40 UTC, matthijsdewit111 commented
Still working on testing horovod with github actions.
(I spend some time trying to run github actions locally, but after spending much time, I'm going to try by just committing changes to git I think and see if I can get it to work)

2021-03-12 15:12 UTC, NicoRenaud requested changes
It seems to be working ! Nicely done !
Could you see if you can get code coverage as well for thenhvd test ?

2021-03-12 15:12 UTC, NicoRenaud commented on .github/workflows/build.yml
> +        pytest horovod_tests -n 2
Great that it works !! 
can  you have coverage as well by adding the --cov-config or something like that ?

2021-03-12 15:12 UTC, NicoRenaud commented on horovod_tests/test_utils.py
> +def second_derivative(xm1, x0, xp1, eps):
I'm not sure the second_derivative is really needed ... my bad

2021-03-12 15:12 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital_horovod.py
> +            clip_loss=False, grad='manual', hdf5_group='optimization',
I will still change the default name to wf_opt :)

2021-03-12 15:12 UTC, NicoRenaud commented on qmctorch/solver/solver_orbital_horovod.py
> +                        self.save_checkpoint(n, cumulative_loss)
Nice !

2021-03-16 15:17 UTC, NicoRenaud approved these changes
Very nice work ! You can merge when you think you're done  (sorry I was so late for approving the PR)

2021-03-16 16:17 UTC, merged